### ISSUE TITLE
"No provider for Client!"

### ISSUE THREAD

**Issue by ptrwis** [angular-examples/toh-6#1]
I was trying to make the example "toh-6" working with "real" back-end, so I commented out the first `main()` in **main.dart**, uncommented the second one, but couldn't make it work (ofc I have written http services). In the browser in console window there was a message "_No provider for Client!_", so I just changed
`provide(BrowserClient, useFactory: () => new BrowserClient(), deps: [])`
to
`provide(Client, useFactory: () => new BrowserClient(), deps: [])`
and it works now, so maybe it's just a simple bug?

**Comment by chalin** [comment]
@ptrwis, thank you for the feedback. That is the proper fix; I'll make the necessary updates soon.

As indicated in the README, can you please re-open this [issue at angular/angular.io](//github.com/angular/angular.io/issues/new?labels=dart,example&title=%5BDart%5D%5Bexample%5D%20tutorial/toh-6%3A%20) and then close this one? This repo is essentially just a read-only mirror.

cc @kwalrath

**Comment by ptrwis** [comment]
Re-opened here https://github.com/angular/angular.io/issues/2055
