### ISSUE TITLE
Un able to Add new hero if we delete all the heros at first

### ISSUE THREAD

**Issue by Capoutcha** [angular-examples/toh-6#2]
starting by deleting the heroes from the list of hero we cant add new heros:
as the _nextId will fail to get any value.
to resolve this without changing your logic:

i just changed the initialization of the InMemoryDataService by adding 
_nextId = _heroesDb.map((hero) => hero.id).reduce(max) + 1;

InMemoryDataService() : super(_handler) {
    _nextId = _heroesDb.map((hero) => hero.id).reduce(max) + 1;
  }

**Comment by chalin** [comment]
Thanks for having reported this issue. 

Some context: in the ToH examples, the initial db has always been populated with some heroes. Deleting all heroes causes no problems (one can add more heroes after that). The reported issue is for the situation where the initial heroes db is empty.

This has been addressed in https://github.com/angular/angular.io/pull/2895
