### ISSUE TITLE
Problem when running the source code for IE11

### ISSUE THREAD

**Issue by DanielTal** [angular-examples/toh-6#3]
The live example of toh-6 runs OK in IE11.
On localhost IIS , we keep getting the following error:
_**EXCEPTION: RangeError (index): Index out of range: no indices are valid: 0**_

we git cloned the example, pub get, pub build and then mapped an IIS site to the build/web output directory of pub build. 
for the rest popular browsers, it works perfectly. 

giving the fact the live example works fine on IE11, I suspect it has something to do with the IIS configuration ? any ideas ?

**Comment by enyo** [comment]
If you mean Microsoft "Internet Information Services" with IIS, then I don't think that it's related. I ran the same example with `pub serve` on a mac machine and got the same error.

**Comment by enyo** [comment]
But you're right... it's very interesting that the live example works fine. I assume that it has to do with a dependency.

**Comment by enyo** [comment]
When you check out the [`gh-pages` branch](https://github.com/angular-examples/toh-6/tree/gh-pages) and serve that, it works fine. So it would be great to know which dependencies they used in that case to get it to work.

**Comment by DanielTal** [comment]
Hi enyo, thanks for the input.
Still same error with the gh-pages branch.

**Comment by enyo** [comment]
That's interesting. I don't get it when I switch to that branch.

**Comment by DanielTal** [comment]
@dergemkr
solved us the problem in this issue
https://github.com/dart-lang/angular2/issues/94
the IE11 doesn't work with the routing when the app is hosted in the root domain.
So moving it to a sub web application and updating the 
<base href="/sub/">
correspondly .
thanks again .
