### ISSUE TITLE
Reloading application 404

### ISSUE THREAD

**Issue by damondouglas** [angular-examples/toh-6#4]
Reloading [hosted copy](http://angular-examples.github.io/toh-6) of this sample results in 404.

<img width="1042" alt="screen shot 2017-05-12 at 9 36 36 pm" src="https://cloud.githubusercontent.com/assets/762456/26022482/68fce1c4-375b-11e7-8bb9-442d7d1c1f10.png">

Realizing this is a known issue documented [here](http://stackoverflow.com/questions/37616385/angular2-routing-gives-404-when-reloading-page), [here](http://stackoverflow.com/questions/40563419/angular2-dart-with-pub-serve-localhost-refresh-page-404), and [here](https://github.com/angular/angular/issues/7728) what is the established solution in a prod environment?  Is it a server side solution?  Thank you for your help.

**Comment by chalin** [comment]
This will be addressed by https://github.com/dart-lang/site-webdev/issues/578. Please track progress using 578.
